name: Create GitHub Secret Action
description: Create or update a secret in the GitHub Actions API.
inputs:
  name:
    description: Name of the secret that you want to create/update
    required: true
  value:
    description: Value of the secret that you want to create/update
    required: true
  location:
    description: Name of a GitHub repository or organization where you want to
      create/update a secret
    required: false
  org_visibility:
    description: Visibility setting for organization secrets. Accepts `all`,
      `private` or a comma-seperated list of GitHub repository IDs
    required: false
    default: 'private'
  pa_token:
    description: Personal access token with permission to modify repository or
      organization secrets
    required: true
outputs:
  status:
    description: HTTP Status Code of the request against the GitHub API that
      created/updated the secret
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: yellow
  icon: eye-off
